sudo: required
addons:
  ssh_known_hosts: 129.213.108.56
services:
- docker

before_install:
- docker build -t azegheru/script-deploy -f Dockerfile.dev .

before_deploy:
- openssl aes-256-cbc -K $encrypted_2be2c668a9e0_key -iv $encrypted_2be2c668a9e0_iv
  -in id_rsa.enc -out /tmp/id_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/id_rsa
- ssh-add /tmp/id_rsa
script:
- docker run -e CI=true azegheru/script-deploy npm run test
deploy:
- provider: script
  skip_cleanup: true
  script: rsync -r --delete-after --quiet $TRAVIS_BUILD_DIR/ ubuntu@129.213.108.56:/home/ubuntu/client

after_deploy: 
- ssh -t ubuntu@129.213.108.56 'cd /home/ubuntu/client; exec $SHELL'
- ssh ubuntu@129.213.108.56 'sudo docker build -t azegheru/script-deploy-prod -f /home/ubuntu/client/Dockerfile .'
- ssh ubuntu@129.213.108.56 'sudo docker run azegheru/script-deploy-prod:latest'
on:
  branch: master
